# Copyright (c) 2024 Junie
# SPDX-License-Identifier: MIT

# Имя клавиатуры при подключении
CONFIG_ZMK_KEYBOARD_NAME="Chary46 Dongle"

# Включаем роль центрального устройства (донгл)
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT=y

# Указываем, что у нас 2 периферийных устройства (левая и правая половины)
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# Максимальное количество соединений (2 половины + 5 Bluetooth профилей)
CONFIG_BT_MAX_CONN=7
CONFIG_BT_MAX_PAIRED=7

# Поддержка ZMK Studio (если нужна на донгле)
CONFIG_ZMK_STUDIO=y

# Повышенная мощность сигнала
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Настройки трекбола и мыши (пробрасываем через донгл)
CONFIG_ZMK_MOUSE=y
